### ISSUE TITLE
Incorporate EpiDoc Example XSLT for transformation

### ISSUE THREAD

**Issue by ajenhl** [EpiDoc/EFES#26] opened 2017-06-22 20:52 UTC
Include the Epidoc example XSLT into EFES, with customisation points corresponding to the XSLT parameters.

This parallels #9.

**Comment by ajenhl** [comment] 2017-06-26 22:54
A design note about this: in the (as yet uncommitted) work I've done on this, I've kept the existing Kiln handling of TEI texts, and added pipelines for handling Epidoc texts. This makes sense to me, both so that EFES stays as close as possible to Kiln and because there will doubtless be projects that have a mixture of the two. I state this here so that if anyone has any objections or thoughts, they can let me know before I go further down this road.

**Comment by gabrielbodard** [comment] 2017-07-06 16:17
How will EFES/users differentiate between EpiDoc and non-EpiDoc TEI files? Will all the former be in subdirectories of /epidoc/ ?

**Comment by ajenhl** [comment] 2017-07-06 20:17
Non-Epidoc TEI files continue to live in content/xml/tei/ and Epidoc files live in content/xml/epidoc/. No doubt issues will arise in terms of when we want to have processes/display handle the two together, and when to keep them apart (eg, search). Having them separate at the most fundamental layer is important, though (for those projects that end up using both).

**Comment by gabrielbodard** [comment] 2017-11-24 12:31
This seems to be a duplicate of #9 , and also complete (with the proviso noted there) so I'm closing it.

**Closed by gabrielbodard** 2017-11-24 12:31 UTC
Labels: WP1 EpiDoc display
